defaults: &defaults
  adapter: postgresql
  encoding: unicode

development:
  <<: *defaults
  database: acts_as_textcaptcha_demo_development

test:
  <<: *defaults
  database: acts_as_textcaptcha_demo_test

production:
  <<: *defaults
  database: acts_as_textcaptcha_demo_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
